service:
  internalPort: 80
ingress:
  tls:
    enabled: false
    secretName: ""
  annotations:
    kubernetes.io/tls-acme: "false"
    kubernetes.io/ingress.class: "traefik"
livenessProbe:
  path: "/probe"
  initialDelaySeconds: 15
  timeoutSeconds: 15
  scheme: "HTTP"
  probeType: "httpGet"
readinessProbe:
  path: "/probe"
  initialDelaySeconds: 5
  timeoutSeconds: 3
  scheme: "HTTP"
  probeType: "httpGet"
persistence:
  enabled: true
  volumeMounts:
    - mountPath: /var/www/storage/data
      subPath: storage_data
    - mountPath: /var/www/storage/app/public
      subPath: storage_public
