<?php

return array(
    ['name' => 'typhoon-dynamics', 'display_name' => '颱風動態', 'children' => [
//        ['name' => 'typhoon-dynamics', 'display_name' => '颱風動態', 'class_name'=>'blcok_type_1','type' => '1'],
        ['name' => 'typhoon-ir', 'display_name' => '颱風IR', 'class_name'=>'blcok_type_1', 'type' => '1'],
        ['name' => 'typhoon-mb', 'display_name' => '颱風MB', 'class_name'=>'blcok_type_1', 'type' => '1'],
        ['name' => 'typhoon-vis', 'display_name' => '颱風VIS', 'class_name'=>'blcok_type_1', 'type'=>'1'],
        ['name' => 'title', 'display_name' => '標題', 'class_name'=>'blcok_type_2', 'type'=>'2'],
        ['name' => 'tool-middle', 'display_name' => '工具列 (中間)', 'class_name'=>'blcok_type_2', 'type'=>'2'],
    ]],['name' => 'typhoon-potential', 'display_name' => '颱風潛勢', 'children' => [
//        ['name' => 'typhoon-potential', 'display_name' => '颱風潛勢', 'class_name'=>'blcok_type_1','type' => '1'],
        ['name' => 'title', 'display_name' => '標題', 'class_name'=>'blcok_type_2', 'type'=>'2'],
        ['name' => 'tool-middle', 'display_name' => '工具列 (中間)', 'class_name'=>'blcok_type_2', 'type'=>'2'],
    ]],['name' => 'wind-observation', 'display_name' => '風力觀測','children' => [
        ['name' => 'taiwan-all', 'display_name' => '台灣 (全)', 'class_name'=>'blcok_type_1', 'type' => '1'],
        ['name' => 'taiwan-n', 'display_name' => '台灣 (北)', 'class_name'=>'blcok_type_1','type' => '1'],
        ['name' => 'taiwan-m', 'display_name' => '台灣 (中)', 'class_name'=>'blcok_type_1','type' => '1'],
        ['name' => 'taiwan-s', 'display_name' => '台灣 (南)', 'class_name'=>'blcok_type_1','type' => '1'],
        ['name' => 'taiwan-e', 'display_name' => '台灣 (東)', 'class_name'=>'blcok_type_1','type' => '1'],
        ['name' => 'title', 'display_name' => '標題', 'class_name'=>'blcok_type_2', 'type'=>'2'],
        ['name' => 'image-tool', 'display_name' => '圖例', 'class_name'=>'blcok_type_2', 'type'=>'2'],
        ['name' => 'tool-left', 'display_name' => '工具列 (左)', 'class_name'=>'blcok_type_2', 'type'=>'2'],
        ['name' => 'tool-right', 'display_name' => '工具列 (右)', 'class_name'=>'blcok_type_2', 'type'=>'2'],
        ['name' => 'tool-middle', 'display_name' => '工具列 (中間)', 'class_name'=>'blcok_type_2', 'type'=>'2'],
    ]],['name' => 'wind-forecast', 'display_name' => '風力預測','children' => [
        ['name' => 'taiwan-all', 'display_name' => '台灣 (全)', 'class_name'=>'blcok_type_1', 'type' => '1'],
        ['name' => 'taiwan-n', 'display_name' => '台灣 (北)', 'class_name'=>'blcok_type_1','type' => '1'],
        ['name' => 'taiwan-m', 'display_name' => '台灣 (中)', 'class_name'=>'blcok_type_1','type' => '1'],
        ['name' => 'taiwan-s', 'display_name' => '台灣 (南)', 'class_name'=>'blcok_type_1','type' => '1'],
        ['name' => 'taiwan-e', 'display_name' => '台灣 (東)', 'class_name'=>'blcok_type_1','type' => '1'],
        ['name' => 'title', 'display_name' => '標題', 'class_name'=>'blcok_type_2', 'type'=>'2'],
        ['name' => 'image-tool', 'display_name' => '圖例', 'class_name'=>'blcok_type_2', 'type'=>'2'],
        ['name' => 'tool-left', 'display_name' => '工具列 (左)', 'class_name'=>'blcok_type_2', 'type'=>'2'],
        ['name' => 'tool-right', 'display_name' => '工具列 (右)', 'class_name'=>'blcok_type_2', 'type'=>'2'],
        ['name' => 'tool-middle', 'display_name' => '工具列 (中間)', 'class_name'=>'blcok_type_2', 'type'=>'2'],
    ]],['name' => 'rainfall-observation', 'display_name' => '雨量觀測','children' => [
        ['name' => 'taiwan-all', 'display_name' => '台灣 (全)', 'class_name'=>'blcok_type_1', 'type' => '1'],
        ['name' => 'taiwan-n', 'display_name' => '台灣 (北)', 'class_name'=>'blcok_type_1','type' => '1'],
        ['name' => 'taiwan-m', 'display_name' => '台灣 (中)', 'class_name'=>'blcok_type_1','type' => '1'],
        ['name' => 'taiwan-s', 'display_name' => '台灣 (南)', 'class_name'=>'blcok_type_1','type' => '1'],
        ['name' => 'taiwan-y', 'display_name' => '台灣 (宜)', 'class_name'=>'blcok_type_1','type' => '1'],
        ['name' => 'taiwan-h', 'display_name' => '台灣 (花)', 'class_name'=>'blcok_type_1','type' => '1'],
        ['name' => 'taiwan-e', 'display_name' => '台灣 (東)', 'class_name'=>'blcok_type_1','type' => '1'],
        ['name' => 'title', 'display_name' => '標題', 'class_name'=>'blcok_type_2', 'type'=>'2'],
        ['name' => 'image-tool', 'display_name' => '圖例', 'class_name'=>'blcok_type_2', 'type'=>'2'],
        ['name' => 'tool-left', 'display_name' => '工具列 (左)', 'class_name'=>'blcok_type_2', 'type'=>'2'],
        ['name' => 'tool-right', 'display_name' => '工具列 (右)', 'class_name'=>'blcok_type_2', 'type'=>'2'],
        ['name' => 'tool-middle', 'display_name' => '工具列 (中間)', 'class_name'=>'blcok_type_2', 'type'=>'2'],
    ]],['name' => 'rainfall-forecast', 'display_name' => '雨量預測','children' => [
        ['name' => 'taiwan-all', 'display_name' => '台灣 (全)', 'class_name'=>'blcok_type_1', 'type' => '1'],
        ['name' => 'taiwan-n', 'display_name' => '台灣 (北)', 'class_name'=>'blcok_type_1','type' => '1'],
        ['name' => 'taiwan-m', 'display_name' => '台灣 (中)', 'class_name'=>'blcok_type_1','type' => '1'],
        ['name' => 'taiwan-s', 'display_name' => '台灣 (南)', 'class_name'=>'blcok_type_1','type' => '1'],
        ['name' => 'taiwan-y', 'display_name' => '台灣 (宜)', 'class_name'=>'blcok_type_1','type' => '1'],
        ['name' => 'taiwan-h', 'display_name' => '台灣 (花)', 'class_name'=>'blcok_type_1','type' => '1'],
        ['name' => 'taiwan-e', 'display_name' => '台灣 (東)', 'class_name'=>'blcok_type_1','type' => '1'],
        ['name' => 'title', 'display_name' => '標題', 'class_name'=>'blcok_type_2', 'type'=>'2'],
        ['name' => 'image-tool', 'display_name' => '圖例', 'class_name'=>'blcok_type_2', 'type'=>'2'],
        ['name' => 'tool-left', 'display_name' => '工具列 (左)', 'class_name'=>'blcok_type_2', 'type'=>'2'],
        ['name' => 'tool-right', 'display_name' => '工具列 (右)', 'class_name'=>'blcok_type_2', 'type'=>'2'],
        ['name' => 'tool-middle', 'display_name' => '工具列 (中間)', 'class_name'=>'blcok_type_2', 'type'=>'2'],
    ]]

);
