<?php

return array(
    ['name' => '颱風動態', 'display_name' => '颱風動態', 'children' => [
        ['name' => '颱風動態', 'display_name' => '颱風動態', 'class_name'=>'blcok_type_1','type' => '1'],
        ['name' => '颱風IR', 'display_name' => '颱風IR', 'class_name'=>'blcok_type_1', 'type' => '1'],
        ['name' => '颱風MB', 'display_name' => '颱風MB', 'class_name'=>'blcok_type_1', 'type' => '1'],
        ['name' => '颱風VIS', 'display_name' => '颱風VIS', 'class_name'=>'blcok_type_1', 'type'=>'1'],
        ['name' => '標題', 'display_name' => '標題', 'class_name'=>'blcok_type_2', 'type'=>'2'],
        ['name' => '工具列_中', 'display_name' => '工具列 (中間)', 'class_name'=>'blcok_type_2', 'type'=>'2'],
    ]],['name' => '颱風潛勢', 'display_name' => '颱風潛勢', 'children' => [
        ['name' => '颱風潛勢', 'display_name' => '颱風潛勢', 'class_name'=>'blcok_type_1','type' => '1'],
        ['name' => '標題', 'display_name' => '標題', 'class_name'=>'blcok_type_2', 'type'=>'2'],
        ['name' => '工具列_中', 'display_name' => '工具列 (中間)', 'class_name'=>'blcok_type_2', 'type'=>'2'],
    ]],['name' => '風力觀測', 'display_name' => '風力觀測','children' => [
        ['name' => '台灣_全', 'display_name' => '台灣 (全)', 'class_name'=>'blcok_type_1', 'type' => '1'],
        ['name' => '台灣_北', 'display_name' => '台灣 (北)', 'class_name'=>'blcok_type_1','type' => '1'],
        ['name' => '台灣_中', 'display_name' => '台灣 (中)', 'class_name'=>'blcok_type_1','type' => '1'],
        ['name' => '台灣_南', 'display_name' => '台灣 (南)', 'class_name'=>'blcok_type_1','type' => '1'],
        ['name' => '台灣_東', 'display_name' => '台灣 (東)', 'class_name'=>'blcok_type_1','type' => '1'],
        ['name' => '標題', 'display_name' => '標題', 'class_name'=>'blcok_type_2', 'type'=>'2'],
        ['name' => '圖例', 'display_name' => '圖例', 'class_name'=>'blcok_type_2', 'type'=>'2'],
        ['name' => '工具列_左', 'display_name' => '工具列 (左)', 'class_name'=>'blcok_type_2', 'type'=>'2'],
        ['name' => '工具列_右', 'display_name' => '工具列 (右)', 'class_name'=>'blcok_type_2', 'type'=>'2'],
        ['name' => '工具列_中', 'display_name' => '工具列 (中間)', 'class_name'=>'blcok_type_2', 'type'=>'2'],
    ]],['name' => '風力預測', 'display_name' => '風力預測','children' => [
        ['name' => '台灣_全', 'display_name' => '台灣 (全)', 'class_name'=>'blcok_type_1', 'type' => '1'],
        ['name' => '台灣_北', 'display_name' => '台灣 (北)', 'class_name'=>'blcok_type_1','type' => '1'],
        ['name' => '台灣_中', 'display_name' => '台灣 (中)', 'class_name'=>'blcok_type_1','type' => '1'],
        ['name' => '台灣_南', 'display_name' => '台灣 (南)', 'class_name'=>'blcok_type_1','type' => '1'],
        ['name' => '台灣_東', 'display_name' => '台灣 (東)', 'class_name'=>'blcok_type_1','type' => '1'],
        ['name' => '標題', 'display_name' => '標題', 'class_name'=>'blcok_type_2', 'type'=>'2'],
        ['name' => '圖例', 'display_name' => '圖例', 'class_name'=>'blcok_type_2', 'type'=>'2'],
        ['name' => '工具列_左', 'display_name' => '工具列 (左)', 'class_name'=>'blcok_type_2', 'type'=>'2'],
        ['name' => '工具列_右', 'display_name' => '工具列 (右)', 'class_name'=>'blcok_type_2', 'type'=>'2'],
        ['name' => '工具列_中', 'display_name' => '工具列 (中間)', 'class_name'=>'blcok_type_2', 'type'=>'2'],
    ]],['name' => '雨量觀測', 'display_name' => '雨量觀測','children' => [
        ['name' => '台灣_全', 'display_name' => '台灣 (全)', 'class_name'=>'blcok_type_1', 'type' => '1'],
        ['name' => '台灣_北', 'display_name' => '台灣 (北)', 'class_name'=>'blcok_type_1','type' => '1'],
        ['name' => '台灣_中', 'display_name' => '台灣 (中)', 'class_name'=>'blcok_type_1','type' => '1'],
        ['name' => '台灣_南', 'display_name' => '台灣 (南)', 'class_name'=>'blcok_type_1','type' => '1'],
        ['name' => '台灣_宜', 'display_name' => '台灣 (宜)', 'class_name'=>'blcok_type_1','type' => '1'],
        ['name' => '台灣_花', 'display_name' => '台灣 (花)', 'class_name'=>'blcok_type_1','type' => '1'],
        ['name' => '台灣_東', 'display_name' => '台灣 (東)', 'class_name'=>'blcok_type_1','type' => '1'],
        ['name' => '標題', 'display_name' => '標題', 'class_name'=>'blcok_type_2', 'type'=>'2'],
        ['name' => '圖例', 'display_name' => '圖例', 'class_name'=>'blcok_type_2', 'type'=>'2'],
        ['name' => '工具列_左', 'display_name' => '工具列 (左)', 'class_name'=>'blcok_type_2', 'type'=>'2'],
        ['name' => '工具列_右', 'display_name' => '工具列 (右)', 'class_name'=>'blcok_type_2', 'type'=>'2'],
        ['name' => '工具列_中', 'display_name' => '工具列 (中間)', 'class_name'=>'blcok_type_2', 'type'=>'2'],
    ]],['name' => '雨量預測', 'display_name' => '雨量預測','children' => [
        ['name' => '台灣_全', 'display_name' => '台灣 (全)', 'class_name'=>'blcok_type_1', 'type' => '1'],
        ['name' => '台灣_北', 'display_name' => '台灣 (北)', 'class_name'=>'blcok_type_1','type' => '1'],
        ['name' => '台灣_中', 'display_name' => '台灣 (中)', 'class_name'=>'blcok_type_1','type' => '1'],
        ['name' => '台灣_南', 'display_name' => '台灣 (南)', 'class_name'=>'blcok_type_1','type' => '1'],
        ['name' => '台灣_宜', 'display_name' => '台灣 (宜)', 'class_name'=>'blcok_type_1','type' => '1'],
        ['name' => '台灣_花', 'display_name' => '台灣 (花)', 'class_name'=>'blcok_type_1','type' => '1'],
        ['name' => '台灣_東', 'display_name' => '台灣 (東)', 'class_name'=>'blcok_type_1','type' => '1'],
        ['name' => '標題', 'display_name' => '標題', 'class_name'=>'blcok_type_2', 'type'=>'2'],
        ['name' => '圖例', 'display_name' => '圖例', 'class_name'=>'blcok_type_2', 'type'=>'2'],
        ['name' => '工具列_左', 'display_name' => '工具列 (左)', 'class_name'=>'blcok_type_2', 'type'=>'2'],
        ['name' => '工具列_右', 'display_name' => '工具列 (右)', 'class_name'=>'blcok_type_2', 'type'=>'2'],
        ['name' => '工具列_中', 'display_name' => '工具列 (中間)', 'class_name'=>'blcok_type_2', 'type'=>'2'],
    ]]

);
